# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

station = Station.create([{ name: 'Arncliffe', mins_from_home: 10 }, { name: 'Wolli Creek', mins_from_home: 15 }])

traintrip = Traintrip.create([{ station_id: 1, train_leaves_at: "8:13" },
                              { station_id: 1, train_leaves_at: "8:23" },
                              { station_id: 1, train_leaves_at: "8:33" },
                              { station_id: 1, train_leaves_at: "8:43" },
                              { station_id: 1, train_leaves_at: "8:53" },
                              { station_id: 1, train_leaves_at: "9:03" },
                              { station_id: 1, train_leaves_at: "9:13" },
                              { station_id: 1, train_leaves_at: "9:23" },
                              { station_id: 1, train_leaves_at: "9:33" },
                              { station_id: 1, train_leaves_at: "9:43" },
                              { station_id: 1, train_leaves_at: "10:03" },
                              { station_id: 1, train_leaves_at: "10:33" },
                              { station_id: 1, train_leaves_at: "11:03" },
                              { station_id: 1, train_leaves_at: "11:33" },
                              { station_id: 1, train_leaves_at: "12:03" },
                              { station_id: 1, train_leaves_at: "12:33" },
                              { station_id: 1, train_leaves_at: "13:03" },
                              { station_id: 1, train_leaves_at: "13:33" },
                              { station_id: 1, train_leaves_at: "14:03" },
                              { station_id: 1, train_leaves_at: "14:33" },
                              { station_id: 1, train_leaves_at: "15:03" },
                              { station_id: 1, train_leaves_at: "15:14" },
                              { station_id: 1, train_leaves_at: "15:24" },
                              { station_id: 1, train_leaves_at: "15:34" },
                              { station_id: 1, train_leaves_at: "15:44" },
                              { station_id: 1, train_leaves_at: "15:54" },
                              { station_id: 1, train_leaves_at: "16:04" },
                              { station_id: 1, train_leaves_at: "16:14" },
                              { station_id: 1, train_leaves_at: "16:24" },
                              { station_id: 1, train_leaves_at: "16:34" },
                              { station_id: 1, train_leaves_at: "16:44" },
                              { station_id: 1, train_leaves_at: "16:54" },
                              { station_id: 1, train_leaves_at: "17:04" },
                              { station_id: 1, train_leaves_at: "17:14" },
                              { station_id: 1, train_leaves_at: "17:24" },
                              { station_id: 1, train_leaves_at: "17:34" },
                              { station_id: 1, train_leaves_at: "17:44" },
                              { station_id: 1, train_leaves_at: "17:54" },
                              { station_id: 1, train_leaves_at: "18:04" },
                              { station_id: 1, train_leaves_at: "18:14" },
                              { station_id: 1, train_leaves_at: "18:24" },
                              { station_id: 1, train_leaves_at: "18:34" },
                              { station_id: 1, train_leaves_at: "18:44" },
                              { station_id: 1, train_leaves_at: "18:54" },
                              { station_id: 1, train_leaves_at: "19:04" },
                              { station_id: 1, train_leaves_at: "19:14" },
                              { station_id: 1, train_leaves_at: "19:33" },
                              { station_id: 1, train_leaves_at: "20:03" },
                              { station_id: 1, train_leaves_at: "20:33" },
                              { station_id: 1, train_leaves_at: "21:03" },
                              { station_id: 1, train_leaves_at: "21:33" },
                              { station_id: 1, train_leaves_at: "22:03" },
                              { station_id: 1, train_leaves_at: "22:33" },
                              { station_id: 1, train_leaves_at: "23:03" },
                              { station_id: 1, train_leaves_at: "23:33" },

                              
                              { station_id: 1, train_leaves_at: "00:03" },
                              { station_id: 1, train_leaves_at: "00:17" }])

                               
traintrip = Traintrip.create([{ station_id: 2, train_leaves_at: "8:03" },
                              { station_id: 2, train_leaves_at: "8:06" },
                              { station_id: 2, train_leaves_at: "8:09" },
                              { station_id: 2, train_leaves_at: "8:12" },
                              { station_id: 2, train_leaves_at: "8:16" },
                              { station_id: 2, train_leaves_at: "8:19" },
                              { station_id: 2, train_leaves_at: "8:23" },
                              { station_id: 2, train_leaves_at: "8:26" },
                              { station_id: 2, train_leaves_at: "8:29" },
                              { station_id: 2, train_leaves_at: "8:32" },
                              { station_id: 2, train_leaves_at: "8:36" },
                              { station_id: 2, train_leaves_at: "8:39" },
                              { station_id: 2, train_leaves_at: "8:43" },
                              { station_id: 2, train_leaves_at: "8:46" },
                              { station_id: 2, train_leaves_at: "8:49" },
                              { station_id: 2, train_leaves_at: "8:52" },
                              { station_id: 2, train_leaves_at: "8:56" },
                              { station_id: 2, train_leaves_at: "8:59" },
                              { station_id: 2, train_leaves_at: "9:03" },
                              { station_id: 2, train_leaves_at: "9:06" },
                              { station_id: 2, train_leaves_at: "9:09" },
                              { station_id: 2, train_leaves_at: "9:12" },
                              { station_id: 2, train_leaves_at: "9:16" },
                              { station_id: 2, train_leaves_at: "9:19" },
                              { station_id: 2, train_leaves_at: "9:23" },
                              { station_id: 2, train_leaves_at: "9:26" },
                              { station_id: 2, train_leaves_at: "9:29" },
                              { station_id: 2, train_leaves_at: "9:36" },
                              { station_id: 2, train_leaves_at: "9:42" },
                              { station_id: 2, train_leaves_at: "9:46" },
                              { station_id: 2, train_leaves_at: "9:57" },
                              { station_id: 2, train_leaves_at: "10:06" },
                              { station_id: 2, train_leaves_at: "10:17" },
                              { station_id: 2, train_leaves_at: "10:20" },
                              { station_id: 2, train_leaves_at: "10:27" },
                              { station_id: 2, train_leaves_at: "10:36" },
                              { station_id: 2, train_leaves_at: "10:47" },

                              { station_id: 2, train_leaves_at: "10:50"},
                              { station_id: 2, train_leaves_at: "10:57"},
                              { station_id: 2, train_leaves_at: "11:06"},
                              { station_id: 2, train_leaves_at: "11:17"},
                              { station_id: 2, train_leaves_at: "11:27"},
                              { station_id: 2, train_leaves_at: "11:36"},
                              { station_id: 2, train_leaves_at: "11:47"},
                              { station_id: 2, train_leaves_at: "11:50"},
                              { station_id: 2, train_leaves_at: "11:57"},
                              { station_id: 2, train_leaves_at: "12:06"},
                              { station_id: 2, train_leaves_at: "12:17"},
                              { station_id: 2, train_leaves_at: "12:27"},
                              { station_id: 2, train_leaves_at: "12:36"},
                              { station_id: 2, train_leaves_at: "12:47"},
                              { station_id: 2, train_leaves_at: "12:50"},
                              { station_id: 2, train_leaves_at: "12:57"},
                              { station_id: 2, train_leaves_at: "13:06"},
                              { station_id: 2, train_leaves_at: "13:17"},
                              { station_id: 2, train_leaves_at: "13:27"},
                              { station_id: 2, train_leaves_at: "13:36"},
                              { station_id: 2, train_leaves_at: "13:47"},
                              { station_id: 2, train_leaves_at: "13:50"},
                              { station_id: 2, train_leaves_at: "13:57"},
                              { station_id: 2, train_leaves_at: "14:06"},
                              { station_id: 2, train_leaves_at: "14:17"},
                              { station_id: 2, train_leaves_at: "14:27"},
                              { station_id: 2, train_leaves_at: "14:36"},
                              { station_id: 2, train_leaves_at: "14:47"},
                              { station_id: 2, train_leaves_at: "14:50"},
                              { station_id: 2, train_leaves_at: "14:57"},
                              { station_id: 2, train_leaves_at: "15:06"},
                              { station_id: 2, train_leaves_at: "15:12"},
                              { station_id: 2, train_leaves_at: "15:17"},
                              { station_id: 2, train_leaves_at: "15:24"},
                              { station_id: 2, train_leaves_at: "15:27"},
                              { station_id: 2, train_leaves_at: "15:31"},
                              { station_id: 2, train_leaves_at: "15:34"},
                              { station_id: 2, train_leaves_at: "15:37"},
                              { station_id: 2, train_leaves_at: "15:42"},
                              { station_id: 2, train_leaves_at: "15:47"},
                              { station_id: 2, train_leaves_at: "15:51"},
                              { station_id: 2, train_leaves_at: "15:54"},
                              { station_id: 2, train_leaves_at: "15:57"},
                              { station_id: 2, train_leaves_at: "16:01"},
                              { station_id: 2, train_leaves_at: "16:04"},
                              { station_id: 2, train_leaves_at: "16:07"},
                              { station_id: 2, train_leaves_at: "16:14"},
                              { station_id: 2, train_leaves_at: "16:17"},
                              { station_id: 2, train_leaves_at: "16:21"},
                              { station_id: 2, train_leaves_at: "16:24"},
                              { station_id: 2, train_leaves_at: "16:27"},
                              { station_id: 2, train_leaves_at: "16:31"},
                              { station_id: 2, train_leaves_at: "16:34"},
                              { station_id: 2, train_leaves_at: "16:37"},
                              { station_id: 2, train_leaves_at: "16:41"},
                              { station_id: 2, train_leaves_at: "16:44"},
                              { station_id: 2, train_leaves_at: "16:47"},
                              { station_id: 2, train_leaves_at: "16:51"},
                              { station_id: 2, train_leaves_at: "16:54"},
                              { station_id: 2, train_leaves_at: "16:57"},
                              { station_id: 2, train_leaves_at: "17:01"},
                              { station_id: 2, train_leaves_at: "17:04"},
                              { station_id: 2, train_leaves_at: "17:07"},
                              { station_id: 2, train_leaves_at: "17:10"},
                              { station_id: 2, train_leaves_at: "17:14"},
                              { station_id: 2, train_leaves_at: "17:17"},
                              { station_id: 2, train_leaves_at: "17:20"},
                              { station_id: 2, train_leaves_at: "17:24"},
                              { station_id: 2, train_leaves_at: "17:27"},
                              { station_id: 2, train_leaves_at: "17:31"},
                              { station_id: 2, train_leaves_at: "17:34"},
                              { station_id: 2, train_leaves_at: "17:37"},
                              { station_id: 2, train_leaves_at: "17:44"},
                              { station_id: 2, train_leaves_at: "17:47"},
                              { station_id: 2, train_leaves_at: "17:50"},
                              { station_id: 2, train_leaves_at: "17:54"},
                              { station_id: 2, train_leaves_at: "17:57"},
                              { station_id: 2, train_leaves_at: "18:04"},
                              { station_id: 2, train_leaves_at: "18:07"},
                              { station_id: 2, train_leaves_at: "18:14"},
                              { station_id: 2, train_leaves_at: "18:17"},
                              { station_id: 2, train_leaves_at: "18:24"},
                              { station_id: 2, train_leaves_at: "18:27"},
                              { station_id: 2, train_leaves_at: "18:34"},
                              { station_id: 2, train_leaves_at: "18:37"},
                              { station_id: 2, train_leaves_at: "18:44"},
                              { station_id: 2, train_leaves_at: "18:47"},
                              { station_id: 2, train_leaves_at: "18:51"},
                              { station_id: 2, train_leaves_at: "18:54"},
                              { station_id: 2, train_leaves_at: "18:57"},
                              { station_id: 2, train_leaves_at: "19:04"},
                              { station_id: 2, train_leaves_at: "19:07"},
                              { station_id: 2, train_leaves_at: "19:12"},
                              { station_id: 2, train_leaves_at: "19:17"},
                              { station_id: 2, train_leaves_at: "19:27"},
                              { station_id: 2, train_leaves_at: "19:36"},
                              { station_id: 2, train_leaves_at: "19:47"},
                              { station_id: 2, train_leaves_at: "19:50"},
                              { station_id: 2, train_leaves_at: "19:57"},
                              { station_id: 2, train_leaves_at: "20:06"},
                              { station_id: 2, train_leaves_at: "20:17"},
                              { station_id: 2, train_leaves_at: "20:27"},
                              { station_id: 2, train_leaves_at: "20:36"},
                              { station_id: 2, train_leaves_at: "20:47"},
                              { station_id: 2, train_leaves_at: "20:50"},
                              { station_id: 2, train_leaves_at: "20:57"},
                              { station_id: 2, train_leaves_at: "21:06"},
                              { station_id: 2, train_leaves_at: "21:17"},
                              { station_id: 2, train_leaves_at: "21:27"},
                              { station_id: 2, train_leaves_at: "21:36"},
                              { station_id: 2, train_leaves_at: "21:47"},
                              { station_id: 2, train_leaves_at: "21:50"},
                              { station_id: 2, train_leaves_at: "21:57"},
                              { station_id: 2, train_leaves_at: "22:06"},
                              { station_id: 2, train_leaves_at: "22:17"},
                              { station_id: 2, train_leaves_at: "22:36"},
                              { station_id: 2, train_leaves_at: "22:47"},
                              { station_id: 2, train_leaves_at: "22:50"},
                              { station_id: 2, train_leaves_at: "23:06"},
                              { station_id: 2, train_leaves_at: "23:17"},
                              { station_id: 2, train_leaves_at: "23:36"},
                              { station_id: 2, train_leaves_at: "23:47"},
                              { station_id: 2, train_leaves_at: "23:50"},
                              

                              { station_id: 2, train_leaves_at: "00:06"},
                              { station_id: 2, train_leaves_at: "00:20"},
                              { station_id: 2, train_leaves_at: "00:53"}])
